@startuml

class Componente <<Component>>{
-precio:Real
+getPrecio():Real
}
class Sanguche {
+setPan(c:Componente)
+setPrincipal(c:Componente)
+setAderezo(c:Componente)
+setAdicional(c:Componente)
}
Sanguche --> Componente : -pan
Sanguche --> Componente : -principal
Sanguche --> Componente : -aderezo
Sanguche --> Componente : -adicional

class Cocinero <<Director>>{
+crearSanguche(b:BuilderSanguche):Sanguche
}

class BuilderSanguche <<Builder>> {
+<<abstract>>componentePan()
+<<abstract>>componentePrincipal()
+<<abstract>>componenteAderezo()
+<<abstract>>componenteAdicional()
+reset()
+getSanguche():Sanguche
}
BuilderSanguche --> Sanguche : -sanguche

class BuilderClasico <<ConcreteBuilder>> extends BuilderSanguche{}
class BuilderVegatariano <<ConcreteBuilder>> extends BuilderSanguche {}
class BuilderVegano <<ConcreteBuilder>> extends BuilderSanguche {}
class BuilderSinTACC <<ConcreteBuilder>> extends BuilderSanguche {}

@enduml

